[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#555555"
blue = "#6f6fff"
cyan = "#55ffff"
green = "#55ff55"
magenta = "#ff55ff"
red = "#ff5555"
white = "#ffffff"
yellow = "#ffff55"

[colors.normal]
black = "#000000"
blue = "#7878ff"
cyan = "#00aaaa"
green = "#00aa00"
magenta = "#aa00aa"
red = "#aa0000"
white = "#c4c4c4"
yellow = "#aa5500"

[colors.primary]
background = "#000000"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "Iosevka Term Extended"

[scrolling]
history = 100000

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window.padding]
x = 5
y = 5

[terminal]
